# Generated by Django 4.2.16 on 2024-10-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='resignation',
            field=models.BooleanField(default=False),
        ),
    ]
