# Generated by Django 4.2.16 on 2024-10-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='journal_entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
