# Generated by Django 4.2.16 on 2024-10-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_game_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
