# Generated by Django 4.2.16 on 2024-10-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_game_is_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_logged_in',
        ),
    ]
